# Generated by Django 4.0.5 on 2022-06-15 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='zip',
            new_name='zipcode',
        ),
    ]
